### ISSUE TITLE
Kindlmann colormap

### ISSUE THREAD

**Issue by vladdez** [JuliaGraphics/ColorSchemes.jl#110]
I think it would be great to implement Kindlman colormap. Description: https://www.kennethmoreland.com/color-advice/

**Comment by cormullion** [comment]
Sounds like a good addition! I’ll get round to adding it later this week, perhaps , but if you or anyone fancy making a PR sooner, go for it!

**Comment by cormullion** [comment]
I've added this - it will be in the next release:

<img width="856" alt="Screenshot 2023-08-02 at 11 11 26" src="https://github.com/JuliaGraphics/ColorSchemes.jl/assets/52289/218a7815-626e-43f2-98c6-6f3bc42e14b8">

**Comment by cormullion** [comment]
There's a strong possiblity of that happening in the near future... :)
