### ISSUE TITLE
Scientific colour maps v8.0

### ISSUE THREAD

**Issue by milankl** [JuliaGraphics/ColorSchemes.jl#112]
v8.0 was released 2 months ago which includes new colour maps, see below. Just as a hint in case you want to include them!

![image](https://github.com/JuliaGraphics/ColorSchemes.jl/assets/25530332/96c71d53-4079-4514-a2af-2dcaef65ed60)

**Comment by cormullion** [comment]
Now updated on master to v8.0.0, will give it a bit of testing before another release (our last release was 2 days ago).

**Comment by cormullion** [comment]
Oops, my mistake! I copied `__init.py__` from his version 8.0 zip

```
"""
    ScientificColourMaps7

    Usage
    -----
    import ScientificColourMaps5 as SCM5
    plt.imshow(data, cmap=SCM5.berlin)

    Available colourmaps
    ---------------------
    acton, bam, bamako, bamO, batlow, batlowK, batlowW, 
    berlin, bilbao, broc, brocO, buda, bukavu, cork, corkO,
    davos, devon, fes, grayC, hawaii, imola, lajolla, lapaz,
    lisbon, nuuk, oleron, oslo, roma, romaO,tofino, tokyo,
    turku, vanimo, vik, vikO
"""
```

but now I see that that is for version 7. :( 

I'll find another list and try again!

**Comment by cormullion** [comment]
I've made another commit, hopefully this is better...

**Comment by milankl** [comment]
It is 🎉 

![image](https://github.com/JuliaGraphics/ColorSchemes.jl/assets/25530332/03ed4c14-fad3-43fd-a257-4adeaad194ab)
