### ISSUE TITLE
PNW colors

### ISSUE THREAD

**Issue by briochemc** [JuliaGraphics/ColorSchemes.jl#113]
Just a suggestion to add these nice colormaps (available in R, mentioned in the [metbrewer](https://github.com/BlakeRMills/MetBrewer#palettes) ReadMe):
- https://github.com/jakelawlor/PNWColors
- https://github.com/karthik/wesanderson

**Comment by cormullion** [comment]
It's now on `#master`. See if it works?!

**Comment by briochemc** [comment]
I did not check master locally, but I see them on the documentation (dev) catalogue! Impressive response time! Thank you!

**Comment by briochemc** [comment]
BTW, not sure here is the best place to mention it, but I just stumbled on this python colormap list that you might find useful: https://pratiman-91.github.io/colormaps/

**Comment by briochemc** [comment]
Not sure if I should I leave this opened until a new release comes out?

**Comment by briochemc** [comment]
ping @cormullion for a new release :)

**Comment by cormullion** [comment]
Soon 😂 This week I updated the docs to use Documenter v1.0 so if they look OK …
