### ISSUE TITLE
Feature request: PerceptualColourMaps integration

### ISSUE THREAD

**Issue by lazarusA** [JuliaGraphics/ColorSchemes.jl#129]
Would it make sense to include here also the collection from https://github.com/peterkovesi/PerceptualColourMaps.jl ? which looks like is not longer maintained. 

mmm... the colormap construction approach seems to be different which might be a stopper.

**Comment by lazarusA** [comment]
ooh... it looks like is mainly Colorcet ( but I cannot find "fire", maybe the naming convention is different, or the list is incomplete).
 
Looking at:

https://colorcet.holoviz.org

Which is already here 😓 ,

**Comment by lazarusA** [comment]
![Screenshot 2024-09-09 at 11 58 16](https://github.com/user-attachments/assets/7ad94e99-55dc-452f-892a-a39aeef8e50d)
found it ! 😄

**Comment by asinghvi17** [comment]
Yeah we already have the colorcet stuff, but it's under the "very descriptive" names :P

**Comment by cormullion** [comment]
I remember finding the naming of these quite difficult. Sometimes they're called `CET-L11` (https://colorcet.com/gallery.html), sometimes `colorwheel, CET_C2s, cyclic_mrybm_35_75_c68_n256_s25` (https://colorcet.holoviz.org). If someone could find a source with all the various naming components and notes attached to the list of color values, I'd could try rebuilding the data file...
