### ISSUE TITLE
All discrete scientific colorschemes are one color short

### ISSUE THREAD

**Issue by kdyrhage** [JuliaGraphics/ColorSchemes.jl#130]
All discrete (i.e. numbered) colorschemes from the scientific suite appear to be one color short, specifically the first color. For example, `colorschemes[:acton10]` contains 9 colors, not the expected 10, and `colorschemes[:acton100]` contains 99 colors. This seems to have been introduced in db7ed7b. I will make a pull request that addresses this issue.

**Comment by cormullion** [comment]
Hi! I might have made an off-by-one error in my code 😂 (I have a script that scans the directory and builds the data files…)
