### ISSUE TITLE
using ColorSchemes Error precompiling

### ISSUE THREAD

**Issue by albz** [JuliaGraphics/ColorSchemes.jl#14]
Hi, I couldn't find a solution for the ColorSchemes building.

When running _using ColorSchemes_ I get the following error:
_Error: Error building `ImageMagick`: 
│ ERROR: LoadError: UndefVarError: is_linux not defined
│ Stacktrace:_

I had force _ is_linux _ to _false_, but it did not solve the issue.

I am using Version 1.0.0 (2018-08-08)

thanks

**Comment by cormullion** [comment]
ColorSchemes doesn't work on version 1.0, because its awaiting progress on the Images.jl stack (which is still stuck on Julia v0.6...). Once Images.jl gets upgraded, I hope to get ColorSchemes working as soon as possible! :)

**Comment by albz** [comment]
Thanks! You probably pointed it out somewhere but didn't find it.
If you check this tweet about plotting lines with a continuous color variation (following a colormap scheme) 
https://twitter.com/albz_marocchino/status/1032011780292333571
I wanted to reproduce it in Julia even simplifying the coding. 
I could so something partial here: https://twitter.com/albz_marocchino/status/1031867908312510464
but convinced myself ColorSchemes could be the right command to write a single line plotting command.

**Comment by cormullion** [comment]
New release should work with v1.0.0...
