### ISSUE TITLE
Turbo color map

### ISSUE THREAD

**Issue by c42f** [JuliaGraphics/ColorSchemes.jl#21]
I just saw the following blog post from the google AI blog which looks like it might fit nicely into this package:

https://ai.googleblog.com/2019/08/turbo-improved-rainbow-colormap-for.html

**Comment by cormullion** [comment]
Good idea! 

I ended up adding the color map colors directly. But I did first try to convert the GLSL code, but I didn't really understand it enough to get the correct results:

```
function turbocolormap(x)
    kRedVec4   = [-0.05195877, 5.18000081, -30.94853351, 81.96403246]
    kGreenVec4 = [0.16207513, 0.17712472, 15.24091500, -36.50657960]
    kBlueVec4  = [0.55305649, 3.00913185, -5.46192616, -11.11819092]
    kRedVec2   = [-86.53476570, 30.23299484]
    kGreenVec2 = [25.95549545, -5.02738237]
    kBlueVec2  = [27.81927491, -14.87899417]
    x = clamp(x, 0.0, 1.0)
    v4 = [1.0, x, x^2, x^3]    
    v4zw = [v4[3], v4[4]]
    v2 = v4zw * v4[3]
    return [
        dot(v4, kRedVec4)   + dot(v2, kRedVec2),
        dot(v4, kGreenVec4) + dot(v2, kGreenVec2),
        dot(v4, kBlueVec4)  + dot(v2, kBlueVec2)
    ]
end
```

**Comment by cormullion** [comment]
added in https://github.com/JuliaGraphics/ColorSchemes.jl/commit/8d988765ab59fc575574e9aec9a38fc3f44bca33

**Comment by c42f** [comment]
Great! I tried translating the GLSL version (https://gist.github.com/mikhailov-work/0d177465a8151eb6ede1768d51d476c7) and I got the same thing. I think it might just somehow have buggy coefficients but perhaps I've forgotten something critical about GLSL.

I made a notebook which computes a better approximation for us:
https://gist.github.com/c42f/f822a7b00258e5c73e27ac4a9db0f418
but I think the sampled version is quite a bit nicer.

**Comment by c42f** [comment]
Looks like it's already made its way into d3 as well: https://observablehq.com/@mbostock/turbo

**Comment by cormullion** [comment]
Nice notebook! You got the same result at first as me, it looks a bit burnt or something at the top end... :)

ColorSchemes is a bit basic, it stores everything as arrays of colors. ColorSchemeTools.jl has a few functions for building schemes with functions, but it's all very simplistic and non-scientific... 

Peter Kovesi's Perceptual Color Maps is the thing, I think.

**Comment by c42f** [comment]
I like that you've got the original sampled colormap in here; I think it's nicer than the polynomial approximation anyway.

I guess this is resolved :+1:
