### ISSUE TITLE
Performance improvements?

### ISSUE THREAD

**Issue by rafaqz** [JuliaGraphics/ColorSchemes.jl#26]
I'm using colorschemes for output in DynamicGrids.jl. But in some case converting simulation output to color can take more time than running the simulation.

It would be good to have a high-performance version of `get` that is always type-stable and doesn't clamp values when they don't need to be clamped. 

Passing nothing for `rangescale` would probably be adequate to do this. Also using StaticArrays may help indexing performance.

We could also specialise on type - types like `Bool` have some obvious optimisations we could use.

Any thoughts before I put something together?

**Comment by cormullion** [comment]
Hi there! Yes, anything you can do to improve this package would be very welcome! Performance hasn’t been a priority till now - I’m mostly concerned with the interface, and this code isn’t a bottleneck for me. Thanks!

**Comment by rafaqz** [comment]
Great! I'm trying to `get` colorschemes 40 million times a second on a laptop, so it's definitely a bottleneck...

I'll have a look at travis as well.

**Comment by cormullion** [comment]
I ended up fixed the travis.yaml file, so as to generate the latest documentation... I've just been adding colorscheme data, not changing the code. I'll probably make a new release soon, but without any code changes (no performance improvements, sorry...!).

**Comment by rafaqz** [comment]
No problem, it might be a while until I get this done anyway
