### ISSUE TITLE
Colormap gallery?

### ISSUE THREAD

**Issue by asinghvi17** [JuliaGraphics/ColorSchemes.jl#29]
It should be possible to have a colormap gallery similar to what MakieGallery does.  The only real work to be done is in the web UI...

**Comment by waldyrious** [comment]
#72 is the same issue, right? If so, for future reference, the commits that fixed it are 689b7498f1fb4b67b111d265293a6ca367788e91 and bae2af1e3d786462ea20a26599a364242dced6fd, both included in the [v3.13 release](https://github.com/JuliaGraphics/ColorSchemes.jl/releases/tag/v3.13.0). The resulting catalogue can be seen here: <https://juliagraphics.github.io/ColorSchemes.jl/stable/catalogue/>.
