### ISSUE TITLE
Seaborn colors?

### ISSUE THREAD

**Issue by isentropic** [JuliaGraphics/ColorSchemes.jl#36]
From python seaborn module.
The work is partially done here
https://github.com/isentropic/PlotThemes.jl/blob/master/src/seaborn.jl
https://github.com/isentropic/PlotThemes.jl/blob/master/src/seaborn_color_gradients.jl
Perhaps someone who knows the conventions of `ColorSchemes` could implement those

**Comment by cormullion** [comment]
I can add those today or tomorrow...

**Comment by isentropic** [comment]
Thanks, seaborn is my favorite colorscheme

**Comment by cormullion** [comment]
Are these the ones? https://juliagraphics.github.io/ColorSchemes.jl/latest/basics/#Seaborn-1

**Comment by isentropic** [comment]
looking good!

**Comment by briochemc** [comment]
Just wanted to point out that, in the docs, the URL provided points to the colorcet colormaps instead of the seaborn ones. I am unsure where the seaborn ones are located so I thought I'd point this here! 🤷

**Comment by cormullion** [comment]
Haha, thanks - copy paste strikes again!
