### ISSUE TITLE
Multiple definition of :grays

### ISSUE THREAD

**Issue by ohmsweetohm1** [JuliaGraphics/ColorSchemes.jl#45]
https://github.com/JuliaGraphics/ColorSchemes.jl/blob/c59e5b621850299101b8b505d9f484d971bb7b80/data/allcolorschemes.jl#L868
https://github.com/JuliaGraphics/ColorSchemes.jl/blob/ffdd1ba781687bc4d412bf010f90ea8ca8e34813/data/cmocean.jl#L2326

**Comment by cormullion** [comment]
Should be fixed in 3.10.0.
