### ISSUE TITLE
Add 15-colorblind friendly palette

### ISSUE THREAD

**Issue by briochemc** [JuliaGraphics/ColorSchemes.jl#51]
Not sure about how it should be named, but this palette could be a nice addition for many categories I guess:

<img width="871" alt="Screen Shot 2020-11-16 at 11 36 48 pm" src="https://user-images.githubusercontent.com/4486578/99253408-cf9dd480-2864-11eb-8d45-de30fc9d1580.png">

Link to poster: http://mkweb.bcgsc.ca/biovis2012/krzywinski-visualizing-biological-data.pdf

Not sure about copyright either.

**Comment by cormullion** [comment]
Reading [this](https://thenode.biologists.com/data-visualization-with-flying-colors/research/) suggests that a max of 8 colors is preferred.

This also recommends the following:
 
![image](https://user-images.githubusercontent.com/52289/99253676-0fcf6980-2809-11eb-8bb9-f035a6267fec.png)

It's easy to add those with these names...

**Comment by briochemc** [comment]
Yes, I agree, my response on slack literally minutes ago was "11 categories is a lot to ask for a colorblind-friendly palette". But then I remembered this one, and thought it could be useful for, well... extreme cases of many categories!

**Comment by briochemc** [comment]
Ha I also remember reading the Paul Tol blog (https://personal.sron.nl/~pault/#sec:qualitative)! These are also pretty nice and would be a nice addition IMHO 😄

**Comment by cormullion** [comment]
I added a few, currently on master.

**Comment by briochemc** [comment]
I think this can be closed then, no? Or should it stay open until this makes it into a release?

**Comment by cormullion** [comment]
No problem - thanks!
