### ISSUE TITLE
Failing test on 3.10.2

### ISSUE THREAD

**Issue by nico202** [JuliaGraphics/ColorSchemes.jl#61]
On my machine, using latest tag, there's a failing test:

```
misc tests: Test Failed at /gnu/store/vjn5iayr1iz6mb40qck86xxr9mpbqiz8-julia-colorschemes-3.10.2/share/julia/packages/ColorSchemes/test/runtests.jl:105
Expression: y2 == y[1]
Evaluated: RGB{Float64}(0.17442110750186596,0.10479916072572365,0.07055654401306825) == RGB{Float64}(0.17442110750186593,0.10479916072572365,0.07055654401306825)
```

**Comment by cormullion** [comment]
😂 Thanks - shouldn't be using `==` there I think...

**Comment by nico202** [comment]
Let's ignore this 0.00000000000000003 difference :')
thanks! :)

**Comment by cormullion** [comment]
trying a fix with https://github.com/JuliaGraphics/ColorSchemes.jl/issues/61 ...

**Comment by nico202** [comment]
Thanks! Last commit does work.  Would you also mind tagging the 3.11 release? I saw the version changed in the project.toml, but no git tag

Thanks!
