### ISSUE TITLE
more colorcet options, glasbey_bw_minc ?

### ISSUE THREAD

**Issue by lazarusA** [JuliaGraphics/ColorSchemes.jl#65]
it seems that the collection of colorcet palettes is not complete, I'm looking for `glasbey_bw_minc_20_minl_30` and its not available, it will be possible to increase the amount of colormaps ? otherwise, what would be the way to define a custom colormap with ColorSchemes with a set of colorants?, in the documentation there is one example but only with two colorants (I did not find a way to make it work for more).

cheers!

**Comment by cormullion** [comment]
Sure, I can add them easily enough!

**Comment by cormullion** [comment]
Hi! Just added these - could you check that they work OK for you?

**Comment by lazarusA** [comment]
Hi, yes, after adding master, I can see and plot with `glasbey`. I suppose all the others also work. Thanks!
