### ISSUE TITLE
[docs] broken URL + spelling clarification

### ISSUE THREAD

**Issue by ptoche** [JuliaGraphics/ColorSchemes.jl#71]
1. If you click on "edit on Github" at https://docs.juliaplots.org/latest/generated/colorschemes/, it takes you to the broken link: https://github.com/JuliaPlots/PlotDocs.jl/blob/master/docs/src/generated/colorschemes.md
2. If you search like so: https://docs.juliaplots.org/latest/search/?q=Colorschemes, you get several links where the spelling is `Colorschemes` instead of `ColorSchemes`. See: https://docs.juliaplots.org/latest/colorschemes/#Colorschemes. I don't think it's intended. It caused me to incorrectly try `Pkg.add("Colorschemes")`.

**Comment by cormullion** [comment]
Hi there! You’re right, there are places where the word is used as a type name, as a general descriptive noun, as a function name, and as a package name. It’s possible there are some inconsistencies in the JuliaPlots documentation’s usage.

But this should be reported and fixed over at JuliaPlots, which uses this package. I can only make edits to the ColorSchemes.jl documentation here in the JuliaGraphics org.

**Comment by ptoche** [comment]
Ooh right. Thanks!
