### ISSUE TITLE
Feature request: Include the web-safe color palette

### ISSUE THREAD

**Issue by adrhill** [JuliaGraphics/ColorSchemes.jl#79]
For some legacy fun, it would be nice to have access to the web-safe color palette.
The full color table can be found [here](https://en.wikipedia.org/wiki/Web_colors#Color_table).

**Comment by cormullion** [comment]
Well, why not! 😃

```
using Colors, ColorSchemes

ColorScheme([parse(RGB, "#$(string(r, base=16))$(string(g, base=16))$(string(b, base=16))") 
        for r in 0x0:3:0xf for g in 0x0:3:0xf for b in 0x0:3:0xf])
```

<img width="770" alt="Screenshot 2021-09-14 at 11 25 02" src="https://user-images.githubusercontent.com/52289/133241239-f7ab0637-73c1-46a7-8785-5087d3373438.png">

Is this a useful order, or would another order be better?

**Comment by adrhill** [comment]
That's a cool one-liner!
The ordering looks good to me too. :)

**Comment by adrhill** [comment]
You could code-golf this even further as
```julia
ColorScheme([parse(RGB, "#$(string.([r,g,b], base=16)...)") for r in 0x0:3:0xf for g in 0x0:3:0xf for b in 0x0:3:0xf])
```
at a small loss of performance.

**Comment by cormullion** [comment]
Cool. Fortunately this package isn't smart enough to generate the schemes in code 😄

**Comment by cormullion** [comment]
added in https://github.com/JuliaGraphics/ColorSchemes.jl/commit/f7d43feee83df88af4b66e3c1ac159d44b604b65

**Comment by adrhill** [comment]
Thanks a lot!
