### ISSUE TITLE
Paul Tols colormaps

### ISSUE THREAD

**Issue by kellertuer** [JuliaGraphics/ColorSchemes.jl#81]
I am currently checking my favourite colours and maps in Julia; I saw that from here

https://personal.sron.nl/~pault/

a lot of colormaps are covered since they are from colorbrewer, though he states that some are “tweaked”. Also he has a discrete rainbow and a sunset as well as the ground colormap. Would it be of interest to add them here, too or are they maybe already covered?

**Comment by cormullion** [comment]
Three of Paul Tol's color-vision-deficient schemes are already included, but if there are any others that would be a useful addition - and different enough to existing ones - I could add them easily enough. 

(I don't know what would be a sensible limit to how many colorschemes could be included here. Probably room for a few more, certainly! :)

**Comment by kellertuer** [comment]
I will carefully check, I think the last one on his page, the ground colormap, might not yet be included. If so, I'll do a PR.

**Comment by cormullion** [comment]
Cool, thanks!
