### ISSUE TITLE
Request: new rangescale option for symmetric colorschemes

### ISSUE THREAD

**Issue by adrhill** [JuliaGraphics/ColorSchemes.jl#88]
I'd be interested in a new `rangescale` option for `get` that automatically centers the rangescale around `(-1, 1) .* maximum(abs, x)` of some input `x`, such that a 0 in the input maps to `0.5` on symmetric color schemes (e.g.`:vik`, `:bwr`, `:curl`, `:balance`, `:delta`).

I would gladly open a PR if I had a clue how to name this option.  😄
Maybe `:symmetric`, `:symmetricextrema`, `:extremasymmetric`?

**Comment by cormullion** [comment]
Nice idea. ‘symmetric’ is good, ‘centered’ or ‘midpoint’ would convey something of the idea.
