### ISSUE TITLE
RdBu and BrBg from matplotlib?

### ISSUE THREAD

**Issue by stevengj** [JuliaGraphics/ColorSchemes.jl#90]
Matplotlib seems like it has finer-granulated versions of these, and they are nice to have as diverging colormaps for signed data.

I like the discussion in Matplotlib's manual here: https://matplotlib.org/stable/tutorials/colors/colormaps.html — it would be nice to have something similar in the documentation, and in particular to highlight which colormaps are perceptually uniform and other nice properties.

**Comment by cormullion** [comment]
Hi! Yes, in earlier releases I used to include figures with a bit more information:

![image](https://user-images.githubusercontent.com/52289/164184938-39c6314e-31e0-4c62-8b62-6edcc3ef1d26.png)

but keeping the size of the swatch docs down became a consideration... And only a proportion of the colorschemes are for plotting purposes... It would be good to add some more information like the one you referenced.

Perhaps we could have a function `perceptual_uniformity(cs::ColorScheme)` that returns some useful information - like a score for suitability?

**Comment by stevengj** [comment]
Maybe just a section of the manual listing a subset of color schemes that are most suitable for visualization, like in Matplotlib's docs?
